### PR TITLE
Transparent background full height. Open browser window

### PR DESCRIPTION
**Pull request by leachjustin18**
@SKempin for some odd reason I'm having trouble assigning this to you.  
 
**Why:** Background was not going all the way down in certain view ports.  
**How:**  Removed restriction on div.  

**Why:** Not opening window on run of gulp watch. 
**How:** Added parameter to gulp task that opens it.  

**Why**: NPM scripts is standard way of firing off applications.
**How**: Added scripts -> start: gulp watch.  Now you just need to run npm start and the rest is done for you.

### CODE REVIEW

**Comment by SKempin** [comment]
@leachjustin18 Thanks, have merged these however the background issue is still persisting?

**Comment by leachjustin18** [comment]
Hmm.  I will look into the background thing again.  Do you mind telling me what the screen size the issue happens at?  I will have a couple ideas, but don't want to submit a false PR.

**Comment by SKempin** [comment]
@leachjustin18 It's happening at wider screen sizes, anything more than 1000 pixels. Thanks.

**Comment by leachjustin18** [comment]
@SKempin I'm not able to replicate the issue of the transparent background not being 100% tall:
background

**Comment by leachjustin18** [comment]
If there is another issue, I'm not sure what it is?

**Comment by leachjustin18** [comment]
If there is.  Please create an issue ticket for it and I will be happy to look into it when I get time

**Comment by SKempin** [comment]
@leachjustin18 I've just tested this again (I'm on a different monitor set up today) and the width does actually seem to be fixed, however I am still getting the issue on a tall window? Are you also experiencing this?

Thanks!

capture

**Comment by SKempin** [comment]
@leachjustin18 Have just fixed this issue.

**Pull request merged**
