### PR TITLE
Replaced missing image with a placeholder

### PR DESCRIPTION
**Pull request by DanWilkes02**
I used a placeholder image (just change the path I added if you don't like the one I chose), saying 'image not found' instead of the default missing image symbol.

### CODE REVIEW

**Comment by SKempin** [comment]
Thanks, however this commit also deletes the `docs` directory (which is the demo). Can you rebuild that with `gulp build:production` and resubmit?

**Comment by DanWilkes02** [comment]
Oh sorry didn't see this message. Yep I'll rebuild like this

**Comment by DanWilkes02** [comment]
Done, my new commit 'Production build' seems to have automatically been updated to the request so it should be good to go

**Review by SKempin — APPROVED** [review]
Thanks!

**Pull request merged**
