### PR TITLE
Added outer container height

### PR DESCRIPTION
**Pull request by benb1983**
So it expands to full browser height

### CODE REVIEW

**Review by SKempin — CHANGES_REQUESTED** [review]
Thanks, however this appears to break the gradient?

**Comment by benb1983** [comment]
I think I see what you mean, I extended the gradient to 100%, is this what you meant?

**Comment by SKempin** [comment]
@benb1983 this breaks the gradient on a widescreen monitor - please see screenshot.

capture

**Review by SKempin — CHANGES_REQUESTED** [review]
This breaks the gradient on a widescreen monitor sorry.

**Comment by benb1983** [comment]
Just changed to Viewport height - what browser are you using, works fine in all supported browsers, landscape and portrait on widescreen monitors for me.

**Pull request closed without merging**
